### ISSUE TITLE
Loose art files must be present during file indexing.

### ISSUE THREAD

**Issue by ghost** [caveman2cosmos/FPKLive#1]
The game doesn't use loose art files if they aren't present during file indexing. That makes it impossible to copy new or changed files into the Assets\art directory. Insted they must be added into a fpk.

**Comment by billw2012** [comment]
Yeah thanks I forgot about that! Easy to make another fpk for patch. I tried the flag on pakbuild but it is just as slow as full build so no use.

**Comment by billw2012** [comment]
I put them into a patch FPK now instead which appears to work great.
